
trigger:
- master
- mr/*

pr:
- master

resources:
  repositories:
    - repository: CImakeshift
      type: github
      name: mbeutel/CImakeshift
      endpoint: mbeutel

jobs:
- template: azure-pipelines/cmake.yml@CImakeshift
  parameters:
    vcpkgRef: 42cc830d874f8e24eb4eb05bd5bb28496e3d498c

    cmakeBuildConfigurations: [Debug, RelWithDebInfo]
    cmakeConfigArgs: '-DSLOWMATH_BUILD_TESTING=ON'
    cmakeTestArgs: '--exclude-regex cuda' # do not run CUDA tests

    targets:

    - os: Windows
      cxxCompiler: MSVC
      cxxCompilerVersions: [VS2019, VS2022]
      platforms: [x86, x64]

    - os: Windows
      cxxCompiler: Clang
      cxxCompilerVersions: [VS2019, VS2022]
      platforms: [x86, x64]

    - os: Windows
      cxxCompiler: MSVC
      cxxCompilerVersions: [VS2022]
      cudaCompiler: NVCC
      cudaCompilerVersions: [11_8]
      platforms: [x64]
      cmakeConfigArgs: '<cmakeConfigArgs> -DSLOWMATH_BUILD_TESTING_CUDA=ON'

    - os: Linux
      cxxCompiler: GCC
      cxxCompilerVersions: [10]
      platforms: [x64]

    - os: Linux
      cxxCompiler: GCC
      cxxCompilerVersions: [12]
      platforms: [x64]
      cxxStandardLibraryDebugMode: true
      cxxSanitizers: [AddressSanitizer, UndefinedBehaviorSanitizer]
      tag: 'sanitize'

    - os: Linux
      cxxCompiler: Clang
      cxxCompilerVersions: [12]
      platforms: [x64]

    - os: Linux
      cxxCompiler: Clang
      cxxCompilerVersions: [14]
      platforms: [x64]
      cxxStandardLibraryDebugMode: true
      cxxSanitizers: [AddressSanitizer, UndefinedBehaviorSanitizer, ImplicitIntegerArithmeticValueChange]
      tag: 'sanitize'

    - os: Linux
      cxxCompiler: GCC
      cxxCompilerVersions: [11]
      cudaCompiler: NVCC
      cudaCompilerVersions: [11_8]
      platforms: [x64]
      cmakeConfigArgs: '<cmakeConfigArgs> -DSLOWMATH_BUILD_TESTING_CUDA=ON'

    - os: MacOS
      cxxCompiler: GCC
      cxxCompilerVersions: [10, 12]
      platforms: [x64]

    - os: MacOS
      cxxCompiler: AppleClang
      cxxCompilerVersions: [13_1_6, 14]
      platforms: [x64]
