
variables:
  system.debug: true

trigger:
- master
- mr/*

pr:
- master

resources:
  repositories:
    - repository: templates
      type: github
      name: mbeutel/CImakeshift
      endpoint: mbeutel
      #ref: refs/tags/0.2

jobs:
- template: azure-pipelines-job-cmake.yml@templates
  parameters:
    vcpkgRef: 5deea3b975fe62990973d73a102de818d83ba20c
    vcpkgOverlayRepo: 'https://mp-force.ziti.uni-heidelberg.de/asc/infrastructure/vcpkg-ports.git'
    vcpkgOverlayRef: 10fe870259f4d716b83cc3792710b47d6b407b16
    vcpkgPackages: ['cmakeshift', 'gsl-lite', 'catch2']

    cmakeBuildConfigurations: [Debug]
    cmakeConfigArgs: '-DSLOWMATH_BUILD_TESTS=ON'
    cmakeTestArgs: '--exclude-regex cuda' # do not run CUDA tests

    targets:

    - os: Windows
      cxxCompiler: MSVC
      cxxCompilerVersions: [19_1, 19_2]
      platforms: [x86, x64]

    - os: Windows
      cxxCompiler: Clang
      cxxCompilerVersions: [9]
      platforms: [x86, x64]

    - os: Windows
      cxxCompiler: MSVC
      cxxCompilerVersions: [19_2]
      cudaCompiler: NVCC
      cudaCompilerVersion: 10_2
      platforms: [x64]
      cmakeConfigArgs: '<cmakeConfigArgs> -DSLOWMATH_BUILD_CUDA_TESTS=ON'

    - os: Linux
      cxxCompiler: GCC
      cxxCompilerVersions: [6, 7, 8]
      platforms: [x64]

    - os: Linux
      cxxCompiler: GCC
      cxxCompilerVersions: [9]
      platforms: [x64]
      tag: 'sanitize'
      vcpkgTriplet: <platform>-<os>-sanitize
      cmakeConfigArgs: '<cmakeConfigArgs> -DCMAKESHIFT_PRIVATE_COMPILE_SETTINGS=runtime-checks;debug-stdlib'

    - os: Linux
      cxxCompiler: Clang
      cxxCompilerVersions: [5, 6, 7, 8]
      platforms: [x64]

    - os: Linux
      cxxCompiler: Clang
      cxxCompilerVersions: [9]
      platforms: [x64]
      tag: 'sanitize'
      vcpkgTriplet: <platform>-<os>-sanitize
      cmakeConfigArgs: '<cmakeConfigArgs> -DCMAKESHIFT_PRIVATE_COMPILE_SETTINGS=runtime-checks;debug-stdlib'

    - os: Linux
      cxxCompiler: GCC
      cxxCompilerVersions: [8]
      cudaCompiler: NVCC
      cudaCompilerVersion: 10_2
      platforms: [x64]
      cmakeConfigArgs: '<cmakeConfigArgs> -DSLOWMATH_BUILD_CUDA_TESTS=ON'

    - os: MacOS
      cxxCompiler: GCC
      cxxCompilerVersions: [6, 7, 8, 9]
      platforms: [x64]

    - os: MacOS
      cxxCompiler: AppleClang
      cxxCompilerVersions: [9_1, 10, 10_0_1, 11]
      platforms: [x64]
