
trigger:
- master
- mr/*

pr:
- master

resources:
  repositories:
    - repository: templates
      type: github
      name: mbeutel/CImakeshift
      endpoint: mbeutel

jobs:
- template: azure-pipelines-job-cmake.yml@templates
  parameters:
    vcpkgRef: e308474b85ff49f2b688a759351c4ec569636910
    vcpkgOverlayRepo: 'https://mp-force.ziti.uni-heidelberg.de/asc/infrastructure/vcpkg-ports.git'
    vcpkgOverlayRef: a08517fb77e9d48d00dd33c16e5acd01f8b31f29
    vcpkgPackages: ['cmakeshift', 'gsl-lite', 'catch2']

    cmakeConfigArgs: '-DSLOWMATH_BUILD_TESTS=ON'

    targets:

    - os: Linux
      cxxCompiler: GCC
      cxxCompilerVersions: [6, 7, 8]
      platforms: [x64]

    - os: Linux
      cxxCompiler: GCC
      cxxCompilerVersions: [9]
      platforms: [x64]
      displayTag: 'sanitize'
      vcpkgTriplet: <platform>-<os>-sanitize
      cmakeConfigArgs: '-DCMAKESHIFT_PRIVATE_COMPILE_SETTINGS=runtime-checks;debug-stdlib'

    - os: Linux
      cxxCompiler: Clang
      cxxCompilerVersions: [5, 6, 7, 8]
      platforms: [x64]

    - os: Linux
      cxxCompiler: Clang
      cxxCompilerVersions: [9]
      platforms: [x64]
      displayTag: 'sanitize'
      vcpkgTriplet: <platform>-<os>-sanitize
      cmakeConfigArgs: '-DCMAKESHIFT_PRIVATE_COMPILE_SETTINGS=runtime-checks;debug-stdlib'

    - os: Linux
      cxxCompiler: GCC
      cxxCompilerVersions: [9]
      cudaCompiler: NVCC
      cudaCompilerVersion: 10_2
      platforms: [x64]
      cmakeConfigArgs: '-DSLOWMATH_BUILD_CUDA_TESTS=ON'

    - os: Windows
      cxxCompiler: MSVC
      cxxCompilerVersions: [19_1, 19_2]
      platforms: [x86, x64]

    - os: Windows
      cxxCompiler: Clang
      cxxCompilerVersions: [9]
      platforms: [x86, x64]

    - os: Windows
      cxxCompiler: MSVC
      cxxCompilerVersions: [19_2]
      cudaCompiler: NVCC
      cudaCompilerVersion: 10_2
      platforms: [x64]
      cmakeConfigArgs: '-DSLOWMATH_BUILD_CUDA_TESTS=ON'

    - os: MacOS
      cxxCompiler: GCC
      cxxCompilerVersions: [6, 7, 8, 9]
      platforms: [x64]

    - os: MacOS
      cxxCompiler: AppleClang
      cxxCompilerVersions: [8_1, 9, 9_1, 10, 10_0_1, 11]
      platforms: [x64]
