# Azure Pipelines configuration

variables:
  system.debug: true
  vcpkgGitRef: f07efb4a1dfebf4f9d55308785e65c74b68de269
  vcpkgPortsOverlayRepo: 'https://mp-force.ziti.uni-heidelberg.de/asc/infrastructure/vcpkg-ports.git'
  vcpkgPortsOverlayRef: 7f5820dd97e8e0e9f8fe430686db3084bf23aa2d
  vcpkgTripletSuffix: ''
  cmakeConfigArgs: '-DSLOWMATH_BUILD_TESTS=ON'
  revision: 4

trigger:
- master
- mr/*

pr:
- master

jobs:
  - job: Windows

    strategy:
      matrix: 
        MSVC_Debug_x86:
          Config: Debug
          Platform: x86
          Compiler: MSVC
        MSVC_Release_x86:
          Config: RelWithDebInfo
          Platform: x86
          Compiler: MSVC
        MSVC_Debug_x64:
          Config: Debug
          Platform: x64
          Compiler: MSVC
        MSVC_Release_x64:
          Config: RelWithDebInfo
          Platform: x64
          Compiler: MSVC
        #Clang_Debug_x86:
        #  Config: Debug
        #  Platform: x86
        #  Compiler: Clang
        #Clang_Release_x86:
        #  Config: RelWithDebInfo
        #  Platform: x86
        #  Compiler: Clang
        #Clang_Debug_x64:
        #  Config: Debug
        #  Platform: x64
        #  Compiler: Clang
        #Clang_Release_x64:
        #  Config: RelWithDebInfo
        #  Platform: x64
        #  Compiler: Clang

    pool:
      name: Azure Pipelines
      vmImage: 'windows-2019'

    steps:
      - template: azure-pipelines-windows.yml

  - job: Ubuntu

    variables:
        vcpkgTripletSuffix: '-sanitize'
        cmakeConfigArgs: '-DSLOWMATH_BUILD_TESTS=ON -DCMAKESHIFT_PRIVATE_COMPILE_SETTINGS=runtime-checks;debug-stdlib'

    strategy:
      matrix: 
        GCC_Debug:
          Config: Debug
          Platform: x64
          Compiler: GCC
        GCC_Release:
          Config: RelWithDebInfo
          Platform: x64
          Compiler: GCC
        Clang_Debug:
          Config: Debug
          Platform: x64
          Compiler: Clang
        Clang_Release:
          Config: RelWithDebInfo
          Platform: x64
          Compiler: Clang

    pool:
      name: Azure Pipelines
      vmImage: 'ubuntu-18.04'

    steps:
      - template: azure-pipelines-linux.yml

  - job: MacOS

    strategy:
      matrix: 
        GCC_Debug:
          Config: Debug
          Platform: x64
          Compiler: GCC
        GCC_Release:
          Config: RelWithDebInfo
          Platform: x64
          Compiler: GCC
        AppleClang_Debug:
          Config: Debug
          Platform: x64
          Compiler: Clang
        AppleClang_Release:
          Config: RelWithDebInfo
          Platform: x64
          Compiler: Clang

    pool:
      name: Azure Pipelines
      vmImage: 'macOS-10.14'
      
    steps:
      - template: azure-pipelines-macos.yml
